spring:
  application:
    name: notes

  #Data source specific configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/secure-notes
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  #JPA specific configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #JWT specific configuration
  app:
    jwtSecret: 562b6f73322d3e423a243534243233492963482b7a274f6c543d5c276e
    jwtExpirationTimeInMs: 172800000